import { env } from 'cloudflare:workers';
import { successStatement, fencedBatch, named, assertOwnedRowAffected, SUCCESS_STATEMENT_NAME, type CommandExecution } from '../control-plane/job-store';
import { CommandError } from '../core/errors';
import { uuid } from '../util';
import { CreateProductPayload, UpdateProductPayload, PublishProductPayload, ArchiveProductPayload, ReplaceProductAssetPayload, AttachProductAssetPayload, RemoveProductAssetPayload, ReorderProductAssetsPayload, RollbackProductPayload, type ReplaceProductAssetCommand } from '../command-schema';

type ProductRow = { id: string; slug: string; title: string; description: string; category: string; price_amount: number | null; price_currency: string; price_display: string | null; minimum_order_quantity: string | null; primary_asset_id: string | null; seo_title_override: string | null; seo_description_override: string | null; og_image_override: string | null; thumbnail_override: string | null; breadcrumb_label_override: string | null; card_excerpt_override: string | null; status: string; published_at: string | null; version: number; created_at: string; updated_at: string };
type ProductAsset = { asset_id: string; role: 'primary' | 'gallery'; position: number };
// Returns a preparation, not a finished asset: the statements travel with it so
// the product command can commit them in its own fenced batch and remain the
// only writer that finalizes the job.
type AssetResolver = (reference: ReplaceProductAssetCommand['reference'], role: string) => Promise<{ result: { assetId: string; reused: boolean }; statements: unknown[] }>;

const fail = (code: string, message: string, details?: Record<string, unknown>) => new CommandError('USER_CORRECTABLE', code, message, false, details);

async function getProduct(id: string) { const row = await env.DB.prepare(`SELECT id,slug,title,description,category,price_amount,price_currency,price_display,minimum_order_quantity,primary_asset_id,seo_title_override,seo_description_override,og_image_override,thumbnail_override,breadcrumb_label_override,card_excerpt_override,status,published_at,version,created_at,updated_at FROM products WHERE id=? LIMIT 1`).bind(id).first<ProductRow>(); if (!row) throw fail('PRODUCT_NOT_FOUND', 'Product was not found.'); return row; }
async function getAssets(id: string) { return (await env.DB.prepare('SELECT asset_id,role,position FROM product_assets WHERE product_id=? ORDER BY role,position').bind(id).all<ProductAsset>()).results || []; }
function snapshot(product: ProductRow, assets: ProductAsset[]) { return { product, assets }; }
async function assertAsset(assetId: string) { if (!/^asset_[a-f0-9]{64}_(original|large|medium|thumbnail|ogp)$/.test(assetId)) throw fail('PRODUCT_ASSET_ID_INVALID', 'Product asset ID is not canonical.'); const asset = await env.DB.prepare("SELECT id FROM assets WHERE id=? AND validation_status='validated' AND r2_key IS NOT NULL AND bytes > 0 LIMIT 1").bind(assetId).first<{ id: string }>(); if (!asset) throw fail('PRODUCT_ASSET_UNUSABLE', 'The requested Product Asset is missing or unavailable.'); }
const job = (execution: CommandExecution, result: unknown, now: string) => successStatement(execution, result, now);
function revision(commandId: string, action: string, id: string, before: unknown, after: unknown, now: string) { return env.DB.prepare('INSERT INTO content_revisions (id,content_type,content_id,action,before_json,after_json,command_id,created_at) VALUES (?,?,?,?,?,?,?,?)').bind(uuid(), 'product', id, action, JSON.stringify(before), JSON.stringify(after), commandId, now); }
function updateStatement(product: ProductRow, expected: number, updates: string, values: unknown[], next: number, now: string) { return env.DB.prepare(`UPDATE products SET ${updates ? `${updates}, ` : ''}version=?,updated_at=? WHERE id=? AND version=?`).bind(...values, next, now, product.id, expected); }
function searchProjection(productId: string, now: string) { return env.DB.prepare(`INSERT INTO search_documents (id,content_type,content_id,title,description,url,thumbnail,category,keywords_json,updated_at) SELECT 'product:' || p.id,'product',p.id,p.title,p.description,'/products/' || p.slug || '/',CASE WHEN a.r2_key IS NULL THEN NULL ELSE '/api/assets/' || replace(a.r2_key,'/','~') || '/' END,p.category,'[]',? FROM products p LEFT JOIN assets a ON a.id=p.primary_asset_id WHERE p.id=? ON CONFLICT(content_type,content_id) DO UPDATE SET title=excluded.title,description=excluded.description,url=excluded.url,thumbnail=excluded.thumbnail,category=excluded.category,updated_at=excluded.updated_at`).bind(now, productId); }
async function commit(execution: CommandExecution, product: ProductRow, expected: number, action: string, before: unknown, after: unknown, statements: unknown[], result: unknown) {
  const now = new Date().toISOString();
  // The product version is a fence, so a product that moved on aborts the batch.
  const results = await fencedBatch(execution, [
    ...statements.map((statement, index) => named(`mutation-${index}`, statement)),
    named('projection', searchProjection(product.id, now)),
    named('revision', revision(execution.commandId, action, product.id, before, after, now)),
    named(SUCCESS_STATEMENT_NAME, job(execution, result, now))
  ], { versionGuards: [{ subject: 'products', expectedVersion: expected, keys: [product.id, expected] }] });
  assertOwnedRowAffected(execution, results);
  return result;
}
function check(product: ProductRow, expected: number) { if (product.version !== expected) throw new CommandError('CONFLICT', 'PRODUCT_VERSION_CONFLICT', 'Product version does not match expectedVersion.', false, { expectedVersion: expected, currentVersion: product.version }); }
function productValues(product: ProductRow, changes: Record<string, unknown>) { return { ...product, ...changes }; }

export async function executeProductCommand(execution: CommandExecution, input: unknown, options: { resolveAssetReference?: AssetResolver } = {}) {
  const command = execution.commandType;
  const commandId = execution.commandId;
  if (command === 'create_product') {
    const p = CreateProductPayload.parse(input); if (p.primaryAssetId) await assertAsset(p.primaryAssetId);
    const id = uuid(), now = new Date().toISOString(), result = { productId: id, slug: p.slug, version: 1, action: command };
    const product = { id, slug: p.slug, title: p.title, description: p.description, category: p.category, price_amount: p.priceAmount, price_currency: p.priceCurrency, price_display: p.priceDisplay, minimum_order_quantity: p.minimumOrderQuantity, primary_asset_id: p.primaryAssetId, seo_title_override: p.seoTitleOverride, seo_description_override: p.seoDescriptionOverride, og_image_override: p.ogImageOverride, thumbnail_override: p.thumbnailOverride, breadcrumb_label_override: p.breadcrumbLabelOverride, card_excerpt_override: p.cardExcerptOverride, status: p.status, published_at: p.publishedAt, version: 1, created_at: now, updated_at: now };
    const statements: unknown[] = [env.DB.prepare('INSERT INTO products (id,slug,title,description,category,price_amount,price_currency,price_display,minimum_order_quantity,primary_asset_id,seo_title_override,seo_description_override,og_image_override,thumbnail_override,breadcrumb_label_override,card_excerpt_override,status,published_at,version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,product.slug,product.title,product.description,product.category,product.price_amount,product.price_currency,product.price_display,product.minimum_order_quantity,product.primary_asset_id,product.seo_title_override,product.seo_description_override,product.og_image_override,product.thumbnail_override,product.breadcrumb_label_override,product.card_excerpt_override,product.status,product.published_at,1,now,now)];
    if (p.primaryAssetId) statements.push(env.DB.prepare('INSERT INTO product_assets (product_id,asset_id,role,position,created_at) VALUES (?,?,?,?,?)').bind(id,p.primaryAssetId,'primary',0,now));
    await fencedBatch(execution, [...statements, searchProjection(id, now), revision(commandId, command, id, null, snapshot(product, p.primaryAssetId ? [{asset_id:p.primaryAssetId,role:'primary',position:0}] : []), now), job(execution, result, now)] as never[]); return result;
  }
  const validated: any = command === 'update_product' ? UpdateProductPayload.parse(input) : command === 'publish_product' ? PublishProductPayload.parse(input) : command === 'archive_product' ? ArchiveProductPayload.parse(input) : command === 'replace_product_asset' ? ReplaceProductAssetPayload.parse(input) : command === 'attach_product_asset' ? AttachProductAssetPayload.parse(input) : command === 'remove_product_asset' ? RemoveProductAssetPayload.parse(input) : command === 'reorder_product_assets' ? ReorderProductAssetsPayload.parse(input) : RollbackProductPayload.parse(input);
  const product = await getProduct(validated.productId); const currentAssets: ProductAsset[] = await getAssets(product.id); const before = snapshot(product, currentAssets);
  if (command === 'update_product') { const p = UpdateProductPayload.parse(input); check(product,p.expectedVersion); const changes = p.changes as Record<string, unknown>; const columns: string[] = []; const values: unknown[] = []; const mapping: Record<string,string> = { slug:'slug', title:'title', description:'description', category:'category', priceAmount:'price_amount', priceCurrency:'price_currency', priceDisplay:'price_display', minimumOrderQuantity:'minimum_order_quantity', seoTitleOverride:'seo_title_override', seoDescriptionOverride:'seo_description_override', ogImageOverride:'og_image_override', thumbnailOverride:'thumbnail_override', breadcrumbLabelOverride:'breadcrumb_label_override', cardExcerptOverride:'card_excerpt_override' }; for (const [key,column] of Object.entries(mapping)) if (key in changes) { columns.push(`${column}=?`); values.push(changes[key]); } const next = product.version + 1, now = new Date().toISOString(), afterProduct = productValues(product, Object.fromEntries(Object.entries(changes).map(([key,value]) => [mapping[key] || key, value]))); const statements: unknown[] = [updateStatement(product,p.expectedVersion,columns.join(','),values,next,now)]; if (changes.slug && changes.slug !== product.slug) statements.push(env.DB.prepare('INSERT OR IGNORE INTO redirects (id,source_path,destination_path,status_code,created_at) VALUES (?,?,?,?,?)').bind(uuid(),`/products/${product.slug}/`,`/products/${changes.slug}/`,301,now)); return commit(execution, product,p.expectedVersion,'update_product',before,snapshot({ ...afterProduct, version: next, updated_at: now } as ProductRow,currentAssets),statements,{productId:product.id,slug:changes.slug || product.slug,version:next,action:command}); }
  if (command === 'publish_product') { const p = PublishProductPayload.parse(input); check(product,p.expectedVersion); const next=product.version+1, now=new Date().toISOString(), publishedAt=p.publishedAt || now; return commit(execution, product,p.expectedVersion,command,before,snapshot({ ...product,status:'published',published_at:publishedAt,version:next,updated_at:now },currentAssets),[updateStatement(product,p.expectedVersion,'status=?,published_at=?',[ 'published', publishedAt],next,now)],{productId:product.id,version:next,action:command}); }
  if (command === 'archive_product') { const p=ArchiveProductPayload.parse(input); check(product,p.expectedVersion); const next=product.version+1,now=new Date().toISOString(); return commit(execution, product,p.expectedVersion,command,before,snapshot({ ...product,status:'archived',version:next,updated_at:now },currentAssets),[updateStatement(product,p.expectedVersion,'status=?',['archived'],next,now)],{productId:product.id,version:next,action:command}); }
  if (command === 'replace_product_asset' || command === 'attach_product_asset') { const p = (command === 'replace_product_asset' ? ReplaceProductAssetPayload : AttachProductAssetPayload).parse(input) as { productId: string; expectedVersion: number; assetId?: string; reference?: ReplaceProductAssetCommand['reference']; role: 'primary'|'gallery'; position: number }; check(product,p.expectedVersion); let assetId=p.assetId; let intakeStatements: unknown[]=[]; if (p.reference) { if (!options.resolveAssetReference) throw fail('PRODUCT_ASSET_INTAKE_UNAVAILABLE','Product Asset provider intake is not available.'); const resolved=await options.resolveAssetReference(p.reference,p.role==='primary'?'hero':'thumbnail'); assetId=resolved.result.assetId; intakeStatements=resolved.statements; } if (!assetId) throw fail('PRODUCT_ASSET_REQUIRED','A canonical Product Asset ID is required.'); await assertAsset(assetId); const next=product.version+1,now=new Date().toISOString(), role=p.role, position=role==='primary'?0:p.position; const nextAssets=command==='replace_product_asset' ? currentAssets.filter((a: ProductAsset)=>!(a.role===role&&a.position===position)).concat([{asset_id:assetId,role,position}]) : currentAssets.concat([{asset_id:assetId,role,position}]); const nextProduct={...product,primary_asset_id:role==='primary'?assetId:product.primary_asset_id,version:next,updated_at:now}; const statements: unknown[]=[...intakeStatements,updateStatement(product,p.expectedVersion,role==='primary'?'primary_asset_id=?':'',[...(role==='primary'?[assetId]:[])],next,now),env.DB.prepare('DELETE FROM product_assets WHERE product_id=? AND role=? AND position=?').bind(product.id,role,position),env.DB.prepare('INSERT INTO product_assets (product_id,asset_id,role,position,created_at) VALUES (?,?,?,?,?)').bind(product.id,assetId,role,position,now)]; return commit(execution, product,p.expectedVersion,command,before,snapshot(nextProduct,nextAssets),statements,{productId:product.id,assetId,role,position,version:next,action:command}); }
  if (command === 'remove_product_asset') { const p=RemoveProductAssetPayload.parse(input); check(product,p.expectedVersion); const next=product.version+1,now=new Date().toISOString(), nextAssets=currentAssets.filter((a: ProductAsset)=>!(a.role===p.role&&a.position===p.position)), nextProduct={...product,primary_asset_id:p.role==='primary'?null:product.primary_asset_id,version:next,updated_at:now}; return commit(execution, product,p.expectedVersion,command,before,snapshot(nextProduct,nextAssets),[updateStatement(product,p.expectedVersion,p.role==='primary'?'primary_asset_id=?':'',[...(p.role==='primary'?[null]:[])],next,now),env.DB.prepare('DELETE FROM product_assets WHERE product_id=? AND role=? AND position=?').bind(product.id,p.role,p.position)],{productId:product.id,version:next,action:command}); }
  if (command === 'reorder_product_assets') { const p=ReorderProductAssetsPayload.parse(input); check(product,p.expectedVersion); const existing=currentAssets.filter((a: ProductAsset)=>a.role===p.role).map((a: ProductAsset)=>a.asset_id); if (new Set(p.assetIds).size!==p.assetIds.length || existing.length!==p.assetIds.length || existing.some((id: string)=>!p.assetIds.includes(id))) throw fail('PRODUCT_ASSET_SET_MISMATCH','Reorder must contain the complete current Asset ID set.'); const next=product.version+1,now=new Date().toISOString(), reordered=p.assetIds.map((asset_id,position)=>({asset_id,role:p.role,position})); const statements: unknown[]=[updateStatement(product,p.expectedVersion,'',[],next,now),env.DB.prepare('DELETE FROM product_assets WHERE product_id=? AND role=?').bind(product.id,p.role),...reordered.map((a: ProductAsset)=>env.DB.prepare('INSERT INTO product_assets (product_id,asset_id,role,position,created_at) VALUES (?,?,?,?,?)').bind(product.id,a.asset_id,a.role,a.position,now))]; return commit(execution, product,p.expectedVersion,command,before,snapshot({...product,version:next,updated_at:now},currentAssets.filter((a: ProductAsset)=>a.role!==p.role).concat(reordered)),statements,{productId:product.id,version:next,action:command}); }
  if (command === 'rollback_product') { const p=RollbackProductPayload.parse(input); check(product,p.expectedVersion); const revisionRow=await env.DB.prepare("SELECT after_json FROM content_revisions WHERE id=? AND content_type='product' AND content_id=? LIMIT 1").bind(p.revisionId,product.id).first<{after_json:string|null}>(); if(!revisionRow?.after_json) throw fail('PRODUCT_REVISION_NOT_FOUND','The requested Product revision was not found.'); let restored: {product: ProductRow;assets:ProductAsset[]}; try { restored=JSON.parse(revisionRow.after_json); } catch { throw fail('PRODUCT_REVISION_INVALID','The requested Product revision is invalid.'); } if(!restored?.product?.id || restored.product.id!==product.id || !Array.isArray(restored.assets)) throw fail('PRODUCT_REVISION_INVALID','The requested Product revision cannot be restored.'); if(restored.product.primary_asset_id) await assertAsset(restored.product.primary_asset_id); for(const asset of restored.assets) await assertAsset(asset.asset_id); const next=product.version+1,now=new Date().toISOString(), rp={...restored.product,version:next,updated_at:now}; const statements: unknown[]=[updateStatement(product,p.expectedVersion,'slug=?,title=?,description=?,category=?,price_amount=?,price_currency=?,price_display=?,minimum_order_quantity=?,primary_asset_id=?,seo_title_override=?,seo_description_override=?,og_image_override=?,thumbnail_override=?,breadcrumb_label_override=?,card_excerpt_override=?,status=?,published_at=?',[rp.slug,rp.title,rp.description,rp.category,rp.price_amount,rp.price_currency,rp.price_display,rp.minimum_order_quantity,rp.primary_asset_id,rp.seo_title_override,rp.seo_description_override,rp.og_image_override,rp.thumbnail_override,rp.breadcrumb_label_override,rp.card_excerpt_override,rp.status,rp.published_at],next,now),env.DB.prepare('DELETE FROM product_assets WHERE product_id=?').bind(product.id),...restored.assets.map((asset)=>env.DB.prepare('INSERT INTO product_assets (product_id,asset_id,role,position,created_at) VALUES (?,?,?,?,?)').bind(product.id,asset.asset_id,asset.role,asset.position,now))]; return commit(execution, product,p.expectedVersion,command,before,snapshot(rp,restored.assets),statements,{productId:product.id,version:next,revisionId:p.revisionId,action:command}); }
  throw new CommandError('FATAL_SYSTEM_ERROR','PRODUCT_COMMAND_NOT_IMPLEMENTED',`Product command not implemented: ${command}`);
}
